// 用户未登录
export const UNAUTHENTICATION = 'UNAUTHENTICATION';

// 用户没有设置密码
export const USER_NOT_SET_PASSWORD = 'USER_NOT_SET_PASSWORD';
// 用户密码验证错误
export const USER_PASSWORD_NOT_COMPARE = 'USER_PASSWORD_NOT_COMPARE';
// 用户不存在
export const USER_NOT_FOUND = 'USER_NOT_FOUND';

// 安全代码验证失败
export const SECURITY_VALIDATE_ERROR = 'SECURITY_VALIDATE_ERROR';
